### ISSUE TITLE
Presentación de patrón Observer. Lunes 5 de Octubre 2015 

### ISSUE THREAD

**Issue by PalmiraMedina** [tectijuana/javapdd#12]
:memo:

**Comment by PalmiraMedina** [comment]
favor de ponerse en contacto con este medio.

**Comment by IoTeacher** [comment]
# Gracias tiene 100 de calificación entrego el Wiki, Pagina y Código !!

**Comment by IoTeacher** [comment]
# 90 No hubo MARKDOWN en la presentación @irvingcastro
