### ISSUE TITLE
Patrón Command - 6/Oct

### ISSUE THREAD

**Issue by Angelkz** [tectijuana/javapdd#16]
Presentaré el miércoles 6 de Oct el patrón Command.

**Comment by IoTeacher** [comment]
@Angelkz Solo hay el dia 6 de octubre

**Comment by Angelkz** [comment]
Entendido, presento el 6 de octubre.

**Comment by AnaTorresPa** [comment]
Tambien tengo el mismo patron, asi que expondre tambien el 6 de oct

**Comment by IoTeacher** [comment]
# @AnaTorresPa y @Angelkz son 100 en Javapdd, gracias por su tiempo.
