### ISSUE TITLE
Seleccionar PDD de nivel diferente.

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/javapdd#17]
Recuerda que puede haber 2 max. por equipo, si ya se expuso categoria **Estructura**, deben moverse a las otras 2 de tal forma para **comprender estas diferencias** de organización de los 23 patrones.

@tectijuana/patrones

**Comment by Darij** [comment]
El patron que escoji con mi compañero Ulises Camacho fue *Observer *la cual
es un patron de *Comportamiento,* decidimos para esta unidad exponer el
patron de *Prototipo,* la cual es un patron de *Construccion* segun nuestro
conocimiento.
Si hay alguna confusion por favor nos podria clarificar? Con gusto
cambiamos de patron si nos estamos equivocando
Gracias


2016-02-24 16:57 GMT-08:00 René Solis <notifications@github.com>:

**Comment by IoTeacher** [comment]
Gracias @Darij
