### ISSUE TITLE
Presentación de PDD Prototype - Jueves 8 de Octubre

### ISSUE THREAD

**Issue by JuanSilvas** [tectijuana/javapdd#18]
Se realizara la presentación del PDD Prototype el dia Jueves 8 deoctubre

**Comment by b081191** [comment]
Tambien tengo ese patron. Lo presentamos juntos o cada quien por su parte?

**Comment by JuanSilvas** [comment]
Al parecer lo presentaremos juntos

**Comment by b081191** [comment]
@JuanSilvas Va hacer como la expo de c# o si tenemos que traer una presentacion!

**Comment by JuanSilvas** [comment]
Sera igual que la expo de c#, unicamente abriremos en github nuestro proyecto junto con el codigo y explicar el readme.md

**Comment by IoTeacher** [comment]
@b081191 @JuanSilvas Gracias por orgranizarse por medio del Git

**Comment by b081191** [comment]
@JuanSilvas Perfecton entonces este jueves presentamos el patron..
oye y tabmbien tienes que estar en ejecucion en netbeans?

**Comment by b081191** [comment]
Documento de presentación patrón Prototype

[Patrón Prototype.docx](https://github.com/tectijuana/javapdd/files/10234/Patron.Prototype.docx)

**Comment by IoTeacher** [comment]
# Calif. 100, @JuanSilvas @b081191
