### ISSUE TITLE
State

### ISSUE THREAD

**Issue by EddyGaelMR** [tectijuana/javapdd#20]
# Patrón State

El patrón State permite a un objeto adaptar su comportamiento en función de su estado interno.

El patrón State proporciona otra solución que consiste en transformar cada estado en una clase. Esta clase incluye los métodos de la clase Pedido dependiendo de los estados confiriendo el comportamiento propio de cada estado.

El programa principal se incluye en la clase Usuario. El programa crea dos pedidos. Borra el primero en el estado Validado, lo que conduce a una puesta a cero. Respecto al segundo, el programa lo borra una vez se encuentra en el estado Entregado, lo cual no tiene efecto alguno. 

public class Usuario 

{ 

 public static void main(String[] args) 

 { 

 Pedido pedido = new Pedido(); 

 pedido.agregaProducto(new Producto("vehiculo 1")); 

 pedido.agregaProducto(new Producto("accesorio 2")); 

 pedido.visualiza(); 

 pedido.estadoSiguiente(); 

 pedido.agregaProducto(new Producto("accesorio 3")); 

 pedido.borra(); 

 pedido.visualiza(); 

 Pedido pedido2 = new Pedido(); 

 pedido2.agregaProducto(new Producto("vehiculo 11")); 

 pedido2.agregaProducto(new Producto("accesorio 21")); 

 pedido2.visualiza(); 

 pedido2.estadoSiguiente(); 

 pedido2.visualiza(); 

 pedido2.estadoSiguiente(); 

 pedido2.borra(); 

 pedido2.visualiza(); 

 } 

} 

La ejecución del programa proporciona el siguiente resultado. 

Contenido del pedido 

Producto: vehiculo 1 

Producto: accesorio 2 

Contenido del pedido 

Contenido del pedido 

Producto: vehiculo 11 

Producto: accesorio 21 

Contenido del pedido 

Producto: vehiculo 11 

Producto: accesorio 21 

Contenido del pedido 

Producto: vehiculo 11 

Producto: accesorio 21

**Comment by enriquezazueta** [comment]
> Compañero @EddyGaelMR me toco compartir el mismo patrón, para que este informado que vamos a exponer juntos el patrón State. @IoTeacher

**Comment by EddyGaelMR** [comment]
muy bien @enriquezazueta a trabajar :+1:  :)
