### ISSUE TITLE
jpdd 5 de octubre

### ISSUE THREAD

**Issue by Alberto14** [tectijuana/javapdd#21]
Como ya he comentado en varias ocasiones el conocimiento de los patrones de diseño es algo clave a la hora de abordar desarrollos y de solucionar problemas .Hoy voy a hablar un poco a detalle de uno de los patrones de diseño mas sencillo ,el patron Singleton . Este patrón de diseño se encarga de que una clase determinada unicamente pueda tener un único objeto.Normalmente una clase puede instanciar todos los que necesite.

Formato: ![Ver Imagen] (http://www.arquitecturajava.com/wp-content/uploads/00111.gif)

Sin embargo una clase que siga el patrón Singleton tiene la peculiaridad de que solo puede instanciar un único objeto .Este tipo de clases son habituales en temas como configurar parámetros generales de la aplicación ya que una vez instanciado el objeto los valores se mantienen y son compartidos  por toda la aplicación. Vamos a configurar una clase con el patrón Singleton, a esta clase la llamaremos Configurador.

Format: ![Alt Text](http://www.arquitecturajava.com/wp-content/uploads/00211.gif)

Java Singleton

Una vez que tenemos claro cual es el concepto de Configurador vamos a crearlo en código .En este caso nuestro configurador almacenará dos valores url, y base de datos que serán compartidos por el resto de Clases de la aplicación.

package com.arquitecturajava;
 
public class Configurador {
 
private String url;
 private String baseDatos;
 private static Configurador miconfigurador;
 
 public  static Configurador getConfigurador(String url,String baseDatos) {
 
 if (miconfigurador==null) {
 
 miconfigurador=new Configurador(url,baseDatos);
 }
 return miconfigurador;
 }
 
 private Configurador(String url,String baseDatos){
 
 this.url=url;
 this.baseDatos=baseDatos;
 
 }
 
public String getUrl() {
 return url;
 }
 
public void setUrl(String url) {
 this.url = url;
 }
 
public String getBaseDatos() {
 return baseDatos;
 }
 
public void setBaseDatos(String baseDatos) {
 this.baseDatos = baseDatos;
 }
}
Para conseguir que una clase sea de tipo Singleton necesitamos en primer lugar que su constructor sea privado. De esa forma ningún programa será capaz de construir objetos de esta tipo . En segundo lugar necesitaremos disponer de una variable estatica privada que almacene una referencia al objeto que vamos a crear a traves del constructor . Por ultimo un método estático publico que se encarga de instanciar el objeto la primera vez y almacenarlo en la variable estática.

Format: ![Alt Text](http://www.arquitecturajava.com/wp-content/uploads/0039.gif)

Una vez aclarado como funciona un Singleton es muy sencillo utilizarle desde un programa ya que basta con invocar al método estático.

package com.arquitecturajava;
 
public class Principal {
 
public static void main(String[] args) {
 
 Configurador c= Configurador.getConfigurador("miurl", "mibaseDatos");
 
 System.out.println(c.getUrl());
 
 System.out.println(c.getBaseDatos());
 
}
 
}
Singleton y ClassLoaders

A veces los patrones pueden sernos muy útiles y a veces pueden no serlo tanto y llevarnos a situaciones problemáticas . Por ejemplo si preguntamos lo siguiente . ¿El patrón Singleton nos genera un único objeto para una clase Java? . La respuesta mas normal es “SI” sin embargo esta no es verdad del todo .La respuesta correcta es que el patron Singleton nos genera un objeto por cada clase cargada en el mismo ClassLoader.¿ Que quiere decir esto?. Pues quiere decir que por ejemplo dos aplicaciones web que cada una tiene su propio WebClassLoader tendrán cada una so propia instancia.

Format: ![Alt Text](http://www.arquitecturajava.com/wp-content/uploads/0047.gif)

Esto en principio no es problemático porque se encuentran aisladas . Ahora bien hay situaciones en las que un administrador de sistemas puede decidir compartir librerias y clases entre distintas aplicaciones.

Format: ![Alt Text](http://www.arquitecturajava.com/wp-content/uploads/0054.gif)

En este caso si podemos tener problemas ya que el objeto Singleton que en principio fue diseñado para configurar una aplicación concreta estará compartido por varias. Mucho ojo sobre como gestionamos este patrón de diseño ya que facilmente causará problema.

<a href="https://www.youtube.com/watch?v=Z06Phxtj13g" target="_blank">
<img src="http://lh6.ggpht.com/_QosbmeyDVxU/S6nChUGLQpI/AAAAAAAAAfw/iy48J6iG0uM/MySynchronizedSingletonJava_thumb3.jpg?imgmax=800" alt="IMAGE ALT TEXT HERE" width="240" height="180" border="10" /></a>

**Comment by IoTeacher** [comment]
# @Alberto14 tiene 100
