### ISSUE TITLE
Presentación de PDD Mediator- Viernes 9 de Octubre 

### ISSUE THREAD

**Issue by DarkWolf3011** [tectijuana/javapdd#23]
Se llevara a cabo la presentacion del Patron Mediator Viernes 9 de Octubre

**Comment by ilianacm** [comment]
Yo voy a participar

**Comment by Alberto80** [comment]
Yo participaré en Mediator :)

**Comment by ilianacm** [comment]
Perfecto, presentamos el viernes :+1:

**Comment by IoTeacher** [comment]
# Tiene 100 @ilianacm @Alberto80 @DarkWolf3011
