### ISSUE TITLE
Abstract PDD

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/javapdd#36]
@alex20078

**Comment by IoTeacher** [comment]
@alex20078 Abstract se lo asignamos.

**Comment by alex20078** [comment]
Exposición Abstract 12 octubre

**Comment by yagnacabrales** [comment]
Exposicion Abstract 12 octubre (;

**Comment by IoTeacher** [comment]
No entregaron?

**Comment by IoTeacher** [comment]
@yagnacabrales se pusieron de acuerdo?

**Comment by IoTeacher** [comment]
# Gracias por las atenciones 100 los @yagnacabrales @alex20078  @leonmonica @abigailmares
