### ISSUE TITLE
PDD Decorator se presentara el dia 6-Octubre-2015

### ISSUE THREAD

**Issue by Miriam140214** [tectijuana/javapdd#7]
<h2> *Descripción del patrón Decorator* 

La utilidad principal del patrón Decorator, es la de dotar de funcionalidades dinámicamente a objetos mediante composición. Es decir, vamos a decorar los objetos para darles más funcionalidad de la que tienen en un principio.

Esto es algo verdaderamente útil cuándo queremos evitar jerarquías de clases complejas. 
La herencia es una herramienta poderosa, pero puede hacer que nuestro diseño sea mucho menos extensible. 

Resumen para nuestro catálogo de patrones:

* Nombre del patrón: Decorator.
* Tipo: patrón estructural.
* Ventajas: podemos añadir responsabilidades a un objeto de forma progresiva y dinámica. Más flexibilidad que con la herencia.
* Desventajas: la principal es que el objeto Decorator no es exactamente igual que la clase que está   decorando, por lo que tenemos que tener cuidado. Además nos podemos encontrar con un diseño de clases muy pequeñas, pero en gran cantidad.
*Patrones similares o relacionados: Adapter o Facade.
* Lo usaremos cuándo: necesitamos añadir funcionalidades a una clase de forma   dinámica,            evitando las jerarquías de clases que se tienen construir en tiempo de compilación.

<h2> *Diagrama UML*
Format: ![Alt Text](https://upload.wikimedia.org/wikipedia/commons/e/e9/Decorator_UML_class_diagram.svg)
 

<h2> *Video* :movie_camera:
<a href="https://www.youtube.com/watch?v=Hm4KE9QdoJ0" target="_blank">
<img src="http://img.youtube.com/vi/77Kw5P5Y73U/0.jpg" alt="IMAGE ALT TEXT HERE" width="240" height="180" border="10" /></a>

**Comment by IoTeacher** [comment]
# @Miriam140214 tiene 100 en JavaPDD
