### ISSUE TITLE
Prototipo

### ISSUE THREAD

**Issue by Ulises-Camacho** [tectijuana/javapdd#8]
@Darij

**Comment by IoTeacher** [comment]
Jóvenes estuve esperando su presentación ? @Darij @Ulises-Camacho

**Comment by Darij** [comment]
Tenativamente expondremos mañana(21 de abril), heroku no es facil

**Comment by IoTeacher** [comment]
@Darij @Ulises-Camacho con 100, gracias muy bien hecho valio la pena la espera.
